name: Publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    publish-docker-image:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
